function ScreenFunctionSPME(Kx, Ky, Kz, L1, L2, L3, alpha, gamma):
    ...
    ...
    for i from -Kx to Kx:
        for j from -Ky to Ky:
            for k from -Kz to Kz:
                if i == 0 and j == 0 and k == 0:
                    continue
                ...
                ...
                ExpFactorInterpolated[i][j][k] = // Store the result of Eq. (3.10) x Eq. (2.16) in a global array
